# -*- coding: utf-8 -*-
"""ecomui.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DwAse7zazxkDT1no80tF-uA2wUlWeX6I
"""

!pip install -q gradio

import gradio as gr

def respond(message, history):
    """Function to handle the UI chat logic."""
    bot_message = get_answer(message)
    return bot_message

# Launch the Gradio Interface
demo = gr.ChatInterface(
    fn=respond,
    title="ShopSmart Support Bot",
    description="Ask questions about ShopSmart's return policy, memberships, and payments.",
    examples=["What is your return policy?", "Can I pay with PayPal?", "What are the benefits of Premium Membership?"]
)

if __name__ == "__main__":
    demo.launch(share=True, debug=True)